### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by Azucena-Tejeda** [SistemasTecTlaxiaco/infografia-Azucena-Tejeda#2]
[infografia.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Azucena-Tejeda/files/7133247/infografia.pdf)

**Comment by IsraelNicolas61** [comment]
Falto creatividad.
Calificación 16/20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
